version: '3.3'

services:
    redis:
        image: 'redis:alpine'
        container_name: 'redis-db'
        restart: always
        ports:
            - '6379:6379'
        volumes:
            - ${RUNTIME_DIR}/redis:/var/lib/redis
        networks:
            - build-net

    postgres:
        image: 'postgres:latest'
        container_name: 'postgres-db'
        ports:
            - "54320:5432"
        volumes:
            - ${RUNTIME_DIR}/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=build
            - POSTGRES_PASSWORD=passwd
        networks:
            - build-net

    remote-dbg:
        image: 'suilteam/remote:ubuntu'
        container_name: 'remote-dbg'
        ports:
            - '2022:22'
        networks:
            - build-net
        volumes:
            - ${RUNTIME_DIR}:/suil

networks:
    build-net:
        driver: bridge
